services:
  backend:
    build: backend/.
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - /efydb:/root/efydb
  frontend:
    build: frontend/.
    ports:
      - 80:4173

volumes:
  data:
