services:
  backend:
    build: backend/.
    restart: on-failure
    volumes:
      - efydb:/root/efydb
  frontend:
    build: 
      context: frontend/.
      args:
        - PUBLIC_API_URL=https://dbapi.efy.ooo

volumes:
  efydb:

